name: Mail on Push

on:
  push:

jobs:
  mail_on_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send mail
        uses: allikvaleria/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Test
          body: Kõik töötab
          to: allikvaleria@gmail.com
          from: Github action
