name: Send email on push

on: [push]
jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Push to ${{ github.repository }}"
          to: "allikvaleria@gmail.com"
          from: ${{ secrets.MAIL_USERNAME }}
          secure: true
          body: |
            New push in repository: ${{ github.repository }}
            Author: ${{ github.event.pusher.name }}
            Message: ${{ github.event.head_commit.message }}


            